### ISSUE TITLE
小米智能摄像机云台版2K-不可用 附文件结构

### ISSUE THREAD

**Issue by pinglun** [tasy5kg/MiCameraVideoExporter#1]
尝试修改折腾一个多小时没能成功…

以下为此型号的内存卡文件结构，因太长有删减
├─log
│      diagnosis.txt
│      messages.121
│      messages.1626741122
│      messages.1626741182
│      messages.1627167842
│      messages.1627171922
│      messages.60
│      
├─MIJIA_RECORD_MOTION
│  ├─1970010108
│  │      motion_record_msg
│  │      
│  ├─2021072108
│  │      motion_record_msg
│  │          
│  ├─2021072415
│  │      motion_record_msg
│  │      
│  └─2021072508
│          motion_record_msg
│          
└─MIJIA_RECORD_VIDEO
    │  .record_msg
    │  op.log
    │  tmp.jpeg
    │  tmp.mp4
    │  
    ├─2021072308                  \\2021年7月23日8点
    │      42M03S_1627051323.jpeg \\预览图
    │      42M03S_1627051323.mp4  \\视频-42分03秒开始
    │      43M03S_1627051383.jpeg
    │      43M03S_1627051383.mp4
    │      44M03S_1627051443.jpeg
    │      44M03S_1627051443.mp4
    │      58M03S_1627052283.jpeg
    │      58M03S_1627052283.mp4
    │      59M03S_1627052343.jpeg
    │      59M03S_1627052343.mp4
    │      
    ├─2021072323
    │      00M03S_1627052403.jpeg
    │      00M03S_1627052403.mp4
    │      01M03S_1627052463.jpeg
    │      01M03S_1627052463.mp4
    │      10M03S_1627053003.jpeg
    │      10M03S_1627053003.mp4
    │      11M03S_1627053063.jpeg
    └─   11M03S_1627053063.mp4

**Comment by pinglun** [comment]
[完整目录.zip](https://github.com/tasy5kg/MiCameraVideoExporter/files/6873320/default.zip)

**Comment by pinglun** [comment]
嗨 绕了个大圈子，修改了批处理里的路径、删除了小时这个变量，就成了。
刚又修改了下让其可以输入路径，现在我再尝试下看看能不能以天为单位导出，大约在此基础上就应该可以自定义时间段的吧
多谢大佬的批处理

**Comment by tasy5kg** [comment]
@pinglun ，感谢反馈，根据你提供的目录结构，我改了一下脚本，试试这个可以用吗？
[小米摄像机视频导出工具-小米智能摄像机云台版2K.txt](https://github.com/tasy5kg/MiCameraVideoExporter/files/6873769/-.2K.txt)
（使用此文件覆盖```小米摄像机视频导出工具.cmd```）

**Comment by pinglun** [comment]
刚测试了下，可用。大佬威武 @tasy5kg
